### ISSUE TITLE
Reswitched holiday icon contest submissions

### ISSUE THREAD

**Issue by 916253** [916253/Reswitched-Holiday-Contest#1]
# Holiday icon contest submissions

Last year, [Nintendo Homebrew](https://discord.gg/C29hYvh) started an annual tradition of community submissions for holiday themed server icons for several holidays in the fall-winter months. 
This year, as Nintendo Homebrew has started their second annual holiday icon competition, the fun is extending over to [Reswitched](https://discord.gg/Zp4CFRR) as well!

Starting off in October, with a spooky-halloween themed contest, users are encouraged to submit edits of the reswitched icon with the theme of the month on this issue page. Users may make as many submissions as they like, but are asked to stick to high quality submissions.

## Examples of desired quality
Below are examples of past submissions from Nintendo Homebrew's icon contests which were of good enough quality to be considered serious submissions. While they are not directly applicable to the Reswitched icon, they convey the quality we're looking for good enough to use as examples.

![](https://cdn.discordapp.com/attachments/270890866820775946/376836820165591040/HB-browser-icon-full-NOVEMBER.png)
![](https://cdn.discordapp.com/attachments/476198700008341506/491781813086322699/NHB_Discord_Icon_Submission_-_Polly_Esther.png)
![](https://cdn.discordapp.com/attachments/196635394077491200/364517005061128202/unknown_4.png)
![](https://cdn.discordapp.com/attachments/231560704363069442/385545496430772235/Christmas_NH.png)

It is preferred that icons are kept flat/cartoony in style, and not using anything 3d or actual objects.

### Good Luck!
We are excited to see what you'll have to bring to the table. Good luck, and most importantly, have fun!

**Comment by lunalik2** [comment]
![unknown-10](https://user-images.githubusercontent.com/40746746/46110382-791b3b00-c1b1-11e8-8e54-48473e769aa4.png)

**Comment by AnnsAnns** [comment]
Since nobody is actually submitting anything:
![refiles](https://user-images.githubusercontent.com/25822956/46479927-71cae180-c7f0-11e8-9539-1943ec7d54cb.png)

**Comment by ThatNerdyPikachu** [comment]
Q u a l i t y

**Comment by ZetaDesigns** [comment]
![reswitchedlogo_halloween](https://user-images.githubusercontent.com/28535968/46776170-b97acd00-cd0a-11e8-96b5-0b6f8e5b89ca.png)

ghostboy made the glowing logo, I just added the stars

this is how it looks as a server icon in comparison:
![unknown 1](https://user-images.githubusercontent.com/28535968/46776211-e929d500-cd0a-11e8-90ba-8d76db83e910.png)

**Comment by 916253** [comment]
Seeing as there haven't been any other submissions since, Ghostboy's icon is the winner!
